apiVersion: apps/v1
kind: Deployment
metadata:
  name: Sports-App-Api-Gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 2
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: apigateway
          image: sujaydas/sportsapp-apigateway
          ports:
            - containerPort: 3001
