apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
