app:
  appname: sports-app-api-gateway
  selectorname: api-gateway
  replicas: 2
  container:
    containername: api-gateway
    imagename: sujaydas/sportsapp-apigateway
    port: 3000

service:
  servicename: api-gateway-service
  servicetype: NodePort
  selectorname: api-gateway
  port: 3000
  protocol: TCP
  targetPort: 3000
  nodePort: 30001

